dist: trusty
language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - "node_modules"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8

script: 
  - yarn travis

notifications:
  slack: tealhawk:$SLACK_KEY
