language: node_js
node_js:
- "7"
- "6"
- "5"
- "4"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
- npm install -g istanbul
- npm install -g istanbul-coveralls

after_success:
- npm run cover