import 'angular'
import 'angular-route'
import 'angular-cookies'

import './00-config'
import './01-controllers'
import './03-blog-service'
import './04-auth-service'
import './05-setup'
import './06-localDraft-service'